app_folder/blueprints/users/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, EmailField, StringField, DateField, TextAreaField
from wtforms.validators import ValidationError, Optional, InputRequired
from .model import User
from flask_login import current_user


class UpdateCredentials(FlaskForm):
    surname = StringField('Surname', [Optional()])
    first_name = StringField('First name', [Optional()])
    password = PasswordField('Password', [InputRequired()])
    email = EmailField("Email", [Optional()])
    username =StringField('Username', [Optional()])
    course = StringField('Course', [Optional()])
    education = StringField('Education', [Optional()])
    about_me = TextAreaField('About me', [Optional()])
    new_password = PasswordField('New password', [Optional()]) 
    headline = TextAreaField('Head line', [Optional()])

    def validate_email(self, email):
        user = User.query.filter_by(username=email.data).first()
        if user:
            raise ValidationError(f'{self.username.data} is not available, choose another username.')

    def validate_password(self, password):
        user = User.query.filter_by(email=current_user.email).first()
        if not user.verify_password(password.data):
            raise ValidationError('Incorrect pasword, we need to verify your account before updating it.')
    
    
class EditPostForm(FlaskForm):
    content = TextAreaField('Content', [InputRequired()])

app_folder/blueprints/users/__init__.py
from flask import Blueprint
from lib.permissions import Permission

user = Blueprint('user', __name__, template_folder="templates", url_prefix='/user')

from app_folder.blueprints.users import views

@user.app_context_processor
def inject_permisstion():
    return dict(Permission=Permission)

app_folder/blueprints/users/views.py
from crypt import methods
from os import abort
from flask import redirect, render_template, request, url_for, flash , current_app, jsonify
from app_folder.blueprints.users import user
from app_folder.blueprints.users.model import User
from flask_login import login_required, current_user
from app_folder.blueprints.users.forms import UpdateCredentials
from app_folder.extensions import db 
from flask import abort
from app_folder.blueprints.pages.models import Post
from lib.permissions import Permission
from .forms import EditPostForm
from lib.verify_login import permission_required


@user.route('/profile/<string:username>')
def profile(username):
    page = request.args.get('page', 1, int)
    user = User.query.filter_by(username=username).first()
    if user.profile_view_count is None and user != current_user:
        user.profile_view_count = 1
    elif user != current_user:   
        user.profile_view_count += 1    
    db.session.commit()
    if user is None:
        abort(404)    
    pagination = Post.query.filter_by(user=user).order_by(Post.date_posted.desc()).paginate(page, current_app.config['LEGIT_POST_PER_PAGE'], error_out=False)
    posts = pagination.items
    return render_template('profile.html', user=user, posts=posts, pagination=pagination)


@user.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = UpdateCredentials()
    if form.validate_on_submit():
        current_user.password = form.password.data
        current_user.email = form.email.data
        current_user.course = form.course.data
        current_user.education = form.education.data
        current_user.about_me = form.about_me.data
        current_user.surname = form.surname.data
        current_user.first_name = form.first_name.data
        current_user.headline = form.headline.data
        db.session.commit()
        flash('Profile updated', 'success')
        return redirect(url_for('user.profile', username=current_user.username))
    form.surname.data = current_user.surname
    form.username.data = current_user.username
    form.first_name.data = current_user.first_name
    form.email.data = current_user.email
    form.course.data = current_user.course
    form.education.data = current_user.education
    form.about_me.data = current_user.about_me
    form.headline.data = current_user.headline
    return render_template('settings.html', form=form)


@user.route('/post/<int:id>')
@login_required
def post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.user:
        post.user.get_user_total_post_views()
    return render_template('post.html', posts=[post])

@user.route('/edit_post/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.user and not current_user.can(Permission.WRITE_ARTICLES):
        abort(404)
    form = EditPostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('user.post', id=post.id))
    form.content.data = post.content
    return render_template('edit_post.html', form=form, post=post)

@user.route('/follow/<string:username>', methods=['GET'])
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username = username).first()
    print(current_user.is_following(user), 'current user status')
    if user is not None and not current_user.is_following(user):
        current_user.follow(user)
        flash(f'You\'re now following {user.username}', 'success')
        return redirect(url_for('user.profile', username=user.username))
    if user is None:
        flash('Invalid user', 'info')
        return redirect(url_for('page.home'))
    
    if current_user.is_following(user):
        flash('You\'re already following this user', 'info')
    return redirect(url_for('user.profile', username=user.username))


@user.route('/unfollow/<string:username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is not None and current_user.is_following(user):
        current_user.unfollow(user)
        flash(f'You\'ve unfollow {user.username}.', 'success')
        return redirect(url_for('user.profile', username=user.username))
    
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('/'))


@user.route('/followers/<string:username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    page = request.args.get('page', 1, int)

    if user is None:
        flash('User not found', 'success')
        return redirect(url_for('page.home'))
    
    follower_pagination = user.followers.paginate(page, current_app.config['LEGIT_FOLLOWERS_PER_PAGE'], error_out=False )
    followed_pagination = user.followed.paginate(page, current_app.config['LEGIT_FOLLOWERS_PER_PAGE'], error_out=False)

    follower = [{'user' : item.follower, 'timestamp' : item.timestamp} for item in follower_pagination.items]
    followed = [ {'user' : item.followed , 'timestamp' : item.timestamp } for item in followed_pagination.items]

    return render_template('followers.html', follower=follower, follower_pagination=follower_pagination, followed_pagination=followed_pagination, followed=followed, user=user)

@user.route('/network/<string:username>')
@login_required
def network(username):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    
    page = request.args.get('page', 1, int)

    follower_pagination = current_user.followers.paginate(page, current_app.config['LEGIT_FOLLOWERS_PER_PAGE'], error_out=False )
    followed_pagination = current_user.followed.paginate(page, current_app.config['LEGIT_FOLLOWERS_PER_PAGE'], error_out=False)

    follower = [{'user' : item.follower, 'timestamp' : item.timestamp} for item in follower_pagination.items]
    followed = [ {'user' : item.followed , 'timestamp' : item.timestamp } for item in followed_pagination.items]

    return render_template('followers.html', follower=follower, follower_pagination=follower_pagination, followed_pagination=followed_pagination, followed=followed, user=user)

app_folder/blueprints/users/templates/edit_post.html
{% extends 'base.html'%}
{% import 'components/render_form.html' as f %}

{% block content %}
<div class="container py-3">
    <form method="POST" >
        {{ form.hidden_tag() }}


        <div class="my-5">
            <div class="form-floating">
                {{ form.content(class="form-control", placeholder="Leave a comment here" , id="floatingTextarea2",
                style="max-height: 350px; min-height: 200px;") }}
                <label for="floatingTextarea2">Your post</label>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <a href="{{url_for('user.post', id=post.id)}}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-success">Update post</button>
        </div>
    </form>
</div>




</div>
{% endblock %}

app_folder/blueprints/users/templates/followers.html
{% extends 'base.html' %}
{% import 'components/pagination.html' as f with context %}

{% block content %}
<div class="followers">

    <div class="user_followers_page">
        <a href="{{url_for('user.profile', username=user.username)}}">
            <h4>{{user.first_name}} {{user.surname}}</h4>
            <span>{{user.username}}</span>
        </a>
    </div>

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile"
                type="button" role="tab" aria-controls="nav-profile" aria-selected="false">
                Follower
            </button>
            <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact"
                type="button" role="tab" aria-controls="nav-contact" aria-selected="false">
                Following
            </button>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            {% if follower %}
            {% for follower in follower %}
            <div class="follower">
                <div class="follower_description">
                    <div class="follower_img">
                        <a href="{{url_for('user.profile', username=follower['user'].username)}}">
                            <img src="{{follower['user'].create_avatar_image(s=50)}}" alt=""
                                class="rounded-circle mb-3">
                        </a>
                    </div>
                    <span class="follower_header">
                        <span>
                            {{follower['user'].username}} since {{moment(follower['timestamp']).fromNow()}}
                        </span>
                    </span>

                </div>
                <div class="follow_user">
                    {% if current_user == follower['user'] %}
                    <a href="#" class="btn btn-primary disable">Follow</a>
                    {% else %}
                    <a href="{{url_for('user.follow', username=follower['user'].username) }}"
                        class="btn btn-primary">Follow</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>You have no follower</p>
            {% endif %}

            <div class="follower_pagination">
                {{ f.render_profile_pagination(follower_pagination, 'user.followers') }}
            </div>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-profile-tab">
            {% if followed %}
            {% for follow in followed %}
            <div class="follower">
                <div class="follower_description">
                    <div class="follower_img">
                        <a href="{{url_for('user.profile', username=follow['user'].username)}}">
                            <img src="{{follow['user'].create_avatar_image(s=50)}}" alt="" class="rounded-circle mb-3">
                        </a>
                    </div>
                    <span class="follower_header">
                        <span>
                            {{follow['user'].username}} since
                        </span>
                        <span>{{moment(follow['timestamp']).fromNow()}}</span>
                    </span>

                </div>
                <div class="follow_user">
                    {% if current_user == follow['user'] %}
                    <a href="#" class="btn btn-primary disable">Follow</a>
                    {% else %}
                    <a href="{{url_for('user.follow', username=follow['user'].username) }}"
                        class="btn btn-primary">Follow</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% endif %}

            <div class="follower_pagination">
                {{ f.render_profile_pagination(followed_pagination, 'user.followers') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app_folder/blueprints/users/templates/post.html
{% extends 'base.html' %}


{% block content %}
<div class="center_post">
    {% for post in posts %}
    {% include "components/post_component.html" %}
    {% endfor %}
</div>
{% endblock %}

app_folder/blueprints/users/templates/profile.html
{% extends "base.html" %}
{% import 'components/pagination.html' as f with context %}

{% block content %}

<section class="mt-4 container">
    <div class="row">
        <div class="my-panel d-flex flex-column col-xm-12 col-md-9">
            <div class="banner">
                <img src="{{url_for('static', filename='images/banner.jpg')}}" alt="" class="img-fluid">
            </div>
            <img src="{{user.create_avatar_image(s=200)}}" alt="" class="h6 rounded-circle img-fluid my-profile-image">
            <div class="user-details mb-4">
                <h3 class="mx-">{{user.surname}} {{user.first_name}} </h3>
                <p>{{user.headline}}</p>
                <p>{{user.education}}</p>
                <p>{{user.course}}</p>
            </div>

            <div>
                {% if current_user.can(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                    <a href="{{url_for('user.follow', username=user.username)}}" class="btn btn-primary">Follow</a>
                {% else %}
                    <a href="{{url_for('user.unfollow', username=user.username)}}" class="btn btn-primary">Unfollow
                    {{user.username}}</a>
                {% endif %}
                {% endif %}
                    <div class="following_follower">
                        <span><a href="{{url_for('user.followers', username=user.username)}}" class="label label-defualt">{{user.followers.count()}}</a> :Followers</span>
                        <span><a href="{{url_for('user.followers', username=user.username)}}" class="label label-defualt">{{user.followed.count()}}</a>: Following</span>
                    </div>
                {% if current_user != user and user.is_following(current_user) %}
                    <span>{{user.username}} follows you</span>
                {% endif %}
                <a href=""></a>
            </div>

            <button type="button" class="btn btn-primary text-start my-4">Your Posts</button>

            {% for post in posts %}
            {% include 'components/post_component.html' %}
            {% endfor %}


            {{ f.render_profile_pagination(pagination, 'user.profile' ) }}

        </div>

        <div class="related-user d-none d-md-block col-md-3">
            <div class="">
                <div class="card">
                    <div class="card-body">
                        <p>People you may Know </p>

                        <hr />

                        <div class="d-flex">
                            <h6><img src="https://randomuser.me/api/portraits/men/22.jpg" alt=""
                                    class="img-fluid rounded-circle likely-people"></h6>
                            <div class="d-flex justify-content-between flex-column mx-3">
                                <h5>Kyle Simpson</h5>
                                <p>FUll-Stack Developer at Facebook</p>
                            </div>
                        </div>

                        <hr />
                        <div class="d-flex">
                            <h6><img src="https://randomuser.me/api/portraits/men/12.jpg" alt=""
                                    class="img-fluid rounded-circle likely-people"></h6>
                            <div class="d-flex justify-content-between flex-column mx-3">
                                <h5>John Doe</h5>
                                <p>FUll-Stack Developer at Tesla</p>
                            </div>
                        </div>
                        <hr />
                        <div class="d-flex">
                            <h6><img src="https://randomuser.me/api/portraits/men/30.jpg" alt=""
                                    class="img-fluid rounded-circle likely-people"></h6>
                            <div class="d-flex justify-content-between flex-column mx-3">
                                <h5>Mark Sentence</h5>
                                <p>FUll-Stack Developer at Apple</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

app_folder/blueprints/users/templates/settings.html
{% extends 'base.html'%}
{% import 'components/render_form.html' as f %}

{% block content %}
<div class="container py-3">
    <form method="POST" action="{{url_for('user.settings')}}">
        {{ form.hidden_tag() }}
        <div class="user-profile">
            <h2>{{current_user.username}} Account</h2>
            <div class="mt-3">
                <h5>Profile</h5>
                <p>The information will be shown publicly, so becareful of what you share.</p>
            </div>

            <div class="my-4">
                <img src="{{current_user.create_avatar_image(s=200)}}" alt=""
                    class="h6 rounded-circle img-fluid profile">
                <input class="mx-4" type="file" name="Change profile pictures" id="">
            </div>
            <div class="row my-3">
                <div class="col-xm-12 col-md-6 mt-xm-2 mt-2">
                    {{ f.render_form_field(form.surname)}}
                </div>
                <div class="col-xm-12 col-md-6 mt-xm-2 mt-2">
                    {{ f.render_form_field(form.first_name) }}
                </div>
            </div>
            <div class="my-3 row">
                <div class="col-xm-12 col-md-8">
                    {{ f.render_form_field(form.email) }}
                </div>
                <div class="col-xm-12 col-md-3 text-end">
                    <a href="{{url_for('auth.update_email_address')}}" class="btn btn-secondary">Change email</a>
                </div>

            </div>
            <div class="form-floating">
                {{ form.username(class="form-control form-control-lg" , disabled=True ,
                placeholder="name@example.com", id="validationServerUsername")}}
                <label>{{form.username.label()}}</label>
            </div>
            <div class="row my-3">
                <div class="col-xm-12 col-md-6 mt-xm-2 mt-2">
                    {{ f.render_form_field(form.course) }}
                </div>
                <div class="col-xm-12 col-md-6 mt-xm-2 mt-2">
                    {{ f.render_form_field(form.education) }}
                </div>
            </div>
            <div class="my-5">
                <div class="form-floating">
                    {{ form.about_me(class="form-control", placeholder="Leave a comment here" , id="floatingTextarea2",
                    style="max-height: 350px; min-height: 200px;") }}
                    <label for="floatingTextarea2">About me...</label>
                </div>
            </div>

            <div class="my-5">
                {{f.render_form_field(form.headline)}}
            </div>

            <div class="d-xm-block d-md-flex justify-content-between">
                <!-- <div class="form-floating col-xm-12 col-md-6 my-3">
                    {{ form.new_password(class="form-control" , id="validationServerUsername")}}
                    <label>{{form.new_password.label()}}</label>
                </div> -->
                {% if form.password.flags.required %}
                <div class="form-floating col-xm-12 col-md-6 my-3">
                    {% if form.password.errors %}
                    <div class="form-group">
                        {{ form.password(class="form-control is-invalid" , id="validationServerUsername")}}

                        <ul class="invalid-feedback" id="validationServerUsernameFeedback">
                            {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg" , placeholder="name@example.com",
                    id="validationServerUsername")}}
                    {% endif %}
                    <label>*{{form.password.label()}}</label>
                </div>
                {% endif %}
            </div>



            <div class="d-flex justify-content-between my-4">
                <a href="{{url_for('user.profile', username=current_user.username)}}"
                    class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-success">Update profile</button>

            </div>
        </div>



    </form>

</div>
{% endblock %}